export const GET_PROJECT_DETAIL_REQUEST = 'GET_PROJECT_DETAIL_REQUEST'
export const GET_PROJECT_DETAIL_SUCCESS = 'GET_PROJECT_DETAIL_SUCCESS'
export const GET_PROJECT_DETAIL_FAIL = 'GET_PROJECT_DETAIL_FAIL'
export const SEARCH_USER_NAME = 'SEARCH_USER_NAME'