export const OPEN_FORM_UPDATE_TASK = 'OPEN_FORM_UPDATE_TASK'
export const CLOSE_FORM_UPDATE_TASK = 'CLOSE_FORM_UPDATE_TASK'
export const GET_TASK_DETAIL = 'GET_TASK_DETAIL'
export const INSERT_COMMENT = 'INSERT_COMMENT'